### ISSUE TITLE
Issue: Pokecursors not appearing

### ISSUE THREAD

**Issue by brenoos** [klauscfhq/hyper-pokemon#31] opened 2018-03-06 17:55 UTC
## Description

pokecursors not apearring

## Theme settings

```
   pokemon: 'random', // Define your favorite pokemon theme
    pokecursor: 'true', // Activate your theme's pokecursor
    pokemonSyntax: 'dark', // Define the color of the terminal tabs
    unibody: 'true', // Define the color of the Hyper window header
    poketab: 'true', // Deactivate your theme's poketab
```

## Environment

manjaro linux 17
Hyper 1.4.8 (stable)
hyper-pokemon 0.3.5

## Additional Information

![screenshot_20180306_145110](https://user-images.githubusercontent.com/16320379/37048995-49605d9a-214e-11e8-832c-375763481dbd.png)

**Comment by klaudiosinani** [comment] 2018-03-23 20:32
I am having trouble reproducing the issue on windows.
Would you mind sharing the content of your `~/.hyper.js` config file?

![hyper_2018-03-23_22-28-16](https://user-images.githubusercontent.com/12670537/37852028-b9df6766-2ee9-11e8-942d-905157ba547a.png)

**Comment by klaudiosinani** [comment] 2018-04-20 21:33
Since the `0.4.0` release, the `pokecursor` feature has been marked as **deprecated**. More info available [here](https://github.com/klauscfhq/hyper-pokemon/releases/tag/v0.4.0).

**Closed as completed** 2023-02-22 15:13 UTC
Labels: bug, linux, deprecated
